#!/usr/bin/env python3
"""Generate the hub's wildcard routing from an instance registry.

WHY THIS EXISTS
    The obvious way to publish per-instance subdomains is one nginx `server` block
    per instance. That is exactly what B2 did (deploy_listen_proxy.sh) and it is
    why adding one instance meant editing the centre's nginx, one `location` per
    frontend asset, and tripping over regex-vs-prefix precedence. At 200 instances
    it is unmanageable.

    So instead: ONE wildcard vhost serves every `<name>.mrrc.vlsc.net`, and the
    only per-instance fact is which loopback port its tunnel claims. That mapping
    lives in a registry file, and this script turns it into nginx `map` syntax.

REGISTRY FORMAT  /etc/mrrc-hub/instances.tsv
    # name          port
    test1           18800
    bg1sb-home      18801

    The port must be inside frps' allowPorts range (see /etc/frp/frps.toml), which
    is also what stops a mistyped tunnel from publishing an arbitrary service.

USAGE
    python3 gen_hub_routes.py [--registry PATH] [--out PATH] [--check]
    --check only validates the registry and prints what would change.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_REGISTRY = Path("/etc/mrrc-hub/instances.tsv")
DEFAULT_OUT = Path("/etc/nginx/conf.d/mrrc-hub-map.conf")
FRPS_CONFIG = Path("/etc/frp/frps.toml")
NAME_RE = re.compile(r"^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$")

HEADER = """# Generated by mrrc_hub/deploy/gen_hub_routes.py — do not edit by hand.
#
# One wildcard vhost serves every <name>.mrrc.vlsc.net; the only per-instance
# fact is which loopback port its tunnel claims. Adding an instance means adding a
# line to /etc/mrrc-hub/instances.tsv and re-running the generator, NOT editing a
# vhost per instance (that is the B2 pattern this replaces).
#
# Names resolve through the *.mrrc.vlsc.net wildcard DNS record; port 0 means
# "no such instance" and the vhost answers 404 rather than guessing.
"""


def allow_ports(path: Path = FRPS_CONFIG) -> tuple[int, int] | None:
    """Read frps' allowPorts range so the registry can be validated against it."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    m = re.search(r"allowPorts\s*=\s*\[\s*\{\s*start\s*=\s*(\d+)\s*,\s*end\s*=\s*(\d+)", text)
    return (int(m.group(1)), int(m.group(2))) if m else None


def load_registry(path: Path) -> tuple[dict[str, int], list[str]]:
    """Return ({name: port}, problems). Comments and blank lines are ignored."""
    mapping: dict[str, int] = {}
    problems: list[str] = []
    seen_ports: dict[int, str] = {}
    if not path.exists():
        return mapping, [f"registry not found: {path}"]
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            problems.append(f"{path}:{lineno}: expected '<name> <port>', got {raw!r}")
            continue
        name, port_text = parts
        if not NAME_RE.match(name):
            problems.append(f"{path}:{lineno}: {name!r} is not a usable subdomain label")
        try:
            port = int(port_text)
        except ValueError:
            problems.append(f"{path}:{lineno}: {port_text!r} is not a port number")
            continue
        if name in mapping:
            problems.append(f"{path}:{lineno}: duplicate name {name!r}")
        if port in seen_ports:
            problems.append(f"{path}:{lineno}: port {port} already used by {seen_ports[port]!r}")
        mapping[name] = port
        seen_ports[port] = name

    rng = allow_ports()
    if rng is None:
        problems.append(f"could not read allowPorts from {FRPS_CONFIG} (range unchecked)")
    else:
        for name, port in mapping.items():
            if not (rng[0] <= port <= rng[1]):
                problems.append(
                    f"{name}: port {port} is outside frps allowPorts {rng[0]}-{rng[1]} "
                    f"— the tunnel would refuse to claim it")
    return mapping, problems


def render(mapping: dict[str, int]) -> str:
    lines = [HEADER, "map $mrrc_instance $mrrc_port {"]
    lines.append("    default 0;")          # unknown instance
    for name in sorted(mapping):
        lines.append(f"    {name} {mapping[name]};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="validate only; write nothing")
    args = ap.parse_args(argv)

    mapping, problems = load_registry(args.registry)
    for p in problems:
        print(f"problem: {p}", file=sys.stderr)
    if problems:
        return 2
    if not mapping:
        print("refusing to generate: the registry is empty (the wildcard vhost would "
              "404 every instance)", file=sys.stderr)
        return 2

    rendered = render(mapping)
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        print(f"{len(mapping)} instance(s): " + ", ".join(f"{n}→{p}" for n, p in sorted(mapping.items())))
        print("up to date" if current == rendered else "would change")
        return 0

    if args.out.exists() and args.out.read_text(encoding="utf-8") == rendered:
        print(f"{args.out}: unchanged ({len(mapping)} instance(s))")
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"{args.out}: written ({len(mapping)} instance(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
